# Site settings
title: Orbit Insights
email: ""
description: "Space, Subcultures & The Future"
baseurl: "/Orbit-Insights"
url: "https://andrew1014.github.io"
twitter_username: ""
github_username: "andrew1014"

# Jekyll configuration
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude:
  - .sass-cache/

# Minimal Mistakes theme configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: custom-home
  - scope:
      type: posts
    values:
      layout: single

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
