# _config.yml

# Site settings
title: Orbit Insights
email: ""
description: "Space, Subcultures & The Future" # Used for Meta description, blog posts, and site RSS feed
baseurl: "/orbit-insights" # the subpath of your site (e.g. /blog) - no trailing slash
url: "https://andrew1014.github.io" # the absolute URL of your site - no trailing slash
twitter_username: ""
github_username: "andrew1014"

# Jekyll configuration
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude:
  - .sass-cache/
  - /assets/

# Minimal Mistakes theme configuration
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
defaults:
  - scope:
      type: posts
    values:
      layout: single
