# Site settings
title: Orbit Insights
email: ""
description: "Space, Subcultures & The Future"
baseurl: "/Orbit-Insights"
url: "https://andrew1014.github.io"
twitter_username: ""
github_username: "andrew1014"

# Jekyll configuration
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude:
  - .sass-cache/
  - _layouts/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
